version: "3"

tasks:

  install:
    desc: Install project dependencies
    cmds:
      - uv sync --extra lg
  
  lint:
    desc: Run linter
    cmds:
      - uv run ruff check --fix .

  format:
    desc: Format code
    cmds:
      - uv run ruff format .

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  detector:generate:
    desc: Generate fake PII data using Presidio Evaluator
    cmds:
      - uv run python -m resources.generate_dataset -c resources/config/generate-dataset-config.yaml -o resources/data -p fake_pii_data -n 200 -l en_US

  detector:evaluate:
    desc: Evaluate PII detection on a JSON dataset
    cmds:
      - uv run python -m resources.evaluate_dataset -i resources/data/fake_pii_data_size_200_en_US.json -o evaluation_output -l en

  detector:prompt_evaluate:
    desc: Evaluate PII detection using prompt-based approach
    cmds:
      - uv run python -m resources.evaluate_prompt --text "John Doe's email is john.doe@example.com" --language "en"

  detector:benchmark:
    desc: Benchmark analyzer performance across multiple dimensions
    cmds:
      - uv run python -m resources.benchmark_analyzer --iterations 5 --models en_core_web_sm